-- BaseEntity는 상속받는 클래스에서 필드를 포함함

-- author 테이블
CREATE TABLE author (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    author_name VARCHAR(20) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255),
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- schedule 테이블
CREATE TABLE schedule (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    author_id BIGINT,
    task LONGTEXT NOT NULL,
    title VARCHAR(100) NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (author_id) REFERENCES author(id) ON DELETE SET NULL
);

-- comment 테이블
CREATE TABLE comment (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    comment LONGTEXT NOT NULL,
    schedule_id BIGINT,
    author_id BIGINT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (schedule_id) REFERENCES schedule(id) ON DELETE CASCADE,
    FOREIGN KEY (author_id) REFERENCES author(id) ON DELETE SET NULL
);
